id: IB0664255
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:02:58+00:00'
last_modified: '2022-06-07T12:30:23.777739+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4879
  title: བོད་ལུགས་གསོ་རིག་གི་རྒྱུན་མཐོང་ནད་འགོག་བཅོས་ཀྱི་དྲི་བ་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '5587':
      image_group_id: I3CN8645
      title: ''
      total_pages: 150
      order: 1
      base_file: 5587.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
